[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = "usdc_test"
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@solidity-parser/=node_modules/@solidity-parser/",
    "truffle/=node_modules/truffle/",
    "forge-std/=lib/forge-std/src/",
]
fs_permissions = [{ access = "read-write", path = "."}]

solc_version= "0.7.5"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
